/**
 * Generates src/data/corpus/entries/index.ts — a barrel file that
 * re-exports every corpus JSON entry as a single map keyed by id.
 *
 * Run with: npm run corpus:entries
 */

import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const ENTRIES_DIR = path.resolve(
  __dirname,
  "../src/data/corpus/entries"
);
const OUT_PATH = path.join(ENTRIES_DIR, "index.ts");

function toCamelCase(kebab: string): string {
  return kebab.replace(/-(.)/g, (_, c: string) => c.toUpperCase());
}

function main() {
  const files = readdirSync(ENTRIES_DIR)
    .filter((f) => f.endsWith(".json"))
    .sort();

  if (files.length === 0) {
    throw new Error(`No JSON entries found in ${ENTRIES_DIR}`);
  }

  const imports = files
    .map((f) => {
      const id = f.replace(".json", "");
      return `import ${toCamelCase(id)} from "./${f}";`;
    })
    .join("\n");

  const entries = files
    .map((f) => {
      const id = f.replace(".json", "");
      return `  "${id}": ${toCamelCase(id)} as TeaEntry,`;
    })
    .join("\n");

  const content = `// Auto-generated by scripts/gen-corpus-entries-index.ts.
// Do not edit by hand. Run \`npm run corpus:entries\` to regenerate.
import type { TeaEntry } from "@/data/corpus/schema";

${imports}

export const corpusEntries: Record<string, TeaEntry> = {
${entries}
};
`;

  writeFileSync(OUT_PATH, content);
  console.log(`Wrote ${files.length} entries to ${OUT_PATH}`);
}

main();
